import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedWeatherWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedNotTouchWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedInicioWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedBarWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedNewsWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedhomewidget/generated/GeneratedHolaMarioTusplantasteextraaronWidget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedBarWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 23.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: TransformHelper.translate(
                    x: 0.50, y: -349.50, z: 0, child: GeneratedGroup1Widget()),
              ),
              Positioned(
                left: 24.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 55.0,
                child: GeneratedHolaMarioTusplantasteextraaronWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 131.0,
                child: GeneratedMenuWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 142.0,
                child: GeneratedWeatherWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 315.0015869140625,
                height: 189.0,
                child: GeneratedNewsWidget(),
              ),
              Positioned(
                left: 158.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 30.0,
                child: GeneratedInicioWidget(),
              )
            ]),
      ),
    ));
  }
}
