import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget3.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget5.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget4.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedContraseaWidget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedNombredeusuarioWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedLeft1Widget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedCalendarWidget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedRegistrarseWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedUsuarioWidget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedNotTouchWidget3.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedusersigninwidget/generated/GeneratedCorreoWidget.dart';

/* Frame UserSignin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserSigninWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget3(),
              ),
              Positioned(
                left: 148.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 30.0,
                child: GeneratedUsuarioWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 12.720000267028809,
                child: GeneratedLeft1Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 26.0,
                child: GeneratedRegistrarseWidget(),
              ),
              Positioned(
                left: 31.639892578125,
                top: 134.0,
                right: null,
                bottom: null,
                width: 271.760009765625,
                height: 27.05976104736328,
                child: GeneratedNombredeusuarioWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 215.2882080078125,
                right: null,
                bottom: null,
                width: 274.760009765625,
                height: 30.05976104736328,
                child: GeneratedCorreoWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 159.2882080078125,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 240.2882080078125,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget4(),
              ),
              Positioned(
                left: 33.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 274.760009765625,
                height: 30.05976104736328,
                child: GeneratedContraseaWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget5(),
              ),
              Positioned(
                left: 91.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 36.0,
                child: GeneratedCalendarWidget1(),
              )
            ]),
      ),
    ));
  }
}
