import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedGroup1Widget4.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedNotTouchWidget7.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedBarWidget4.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedTimeCircle1Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedRefresh1Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedFrame1Widget5.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget/generated/GeneratedRecordWidget.dart';

/* Frame VRPlant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVRPlantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget7(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedBarWidget4(),
              ),
              Positioned(
                left: 32.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 23.0,
                child: GeneratedFrame1Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 641.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 658.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 54.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedTimeCircle1Widget(),
              ),
              Positioned(
                left: 161.27999877929688,
                top: 672.313232421875,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedRecordWidget(),
              ),
              Positioned(
                left: 271.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedRefresh1Widget(),
              )
            ]),
      ),
    ));
  }
}
