import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedNotTouchWidget13.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedLeft1Widget8.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedElcafesbuenoparalasplantasporquelesbrindaimportantesnut.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedRectangle8Widget23.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedBarWidget10.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedFrame1Widget11.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedPlantWidget5.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedmoreinfodetailwidget/generated/GeneratedGroup1Widget10.dart';

/* Frame MoreInfoDetail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMoreInfoDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedBarWidget10(),
              ),
              Positioned(
                left: 32.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 23.0,
                child: GeneratedFrame1Widget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget13(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 205.1928253173828,
                child: GeneratedPlantWidget5(),
              ),
              Positioned(
                left: 20.15999984741211,
                top: 96.95478820800781,
                right: null,
                bottom: null,
                width: 24.0,
                height: 12.666223526000977,
                child: GeneratedLeft1Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 534.0,
                child: GeneratedRectangle8Widget23(),
              ),
              Positioned(
                left: 26.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 314.0,
                height: 496.0,
                child:
                    GeneratedElcafesbuenoparalasplantasporquelesbrindaimportantesnut(),
              )
            ]),
      ),
    ));
  }
}
