import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedWaterWidget3.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedGroup1Widget3.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedDetailsWidget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedWaterWidget4.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedFrame1Widget4.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedBarWidget3.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedNotTouchWidget6.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedWaterWidget5.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget1/generated/GeneratedPlantWidget1.dart';

/* Frame DetailPlant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailPlantWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget6(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 448.0,
                child: GeneratedPlantWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 324.0,
                child: GeneratedDetailsWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 141.0,
                child: GeneratedWaterWidget3(),
              ),
              Positioned(
                left: 130.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 141.0,
                child: GeneratedWaterWidget4(),
              ),
              Positioned(
                left: 240.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 141.0,
                child: GeneratedWaterWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedBarWidget3(),
              ),
              Positioned(
                left: 32.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 23.0,
                child: GeneratedFrame1Widget4(),
              )
            ]),
      ),
    ));
  }
}
