import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget10.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedGroup1Widget6.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedLeft1Widget6.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedNotTouchWidget9.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedDetailsWidget3.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedPlantWidget3.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget9.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatededitplantwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget11.dart';

/* Frame EditPlant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditPlantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget9(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 101.07437133789062,
                child: GeneratedPlantWidget3(),
              ),
              Positioned(
                left: 20.159912109375,
                top: 97.718505859375,
                right: null,
                bottom: null,
                width: 24.0,
                height: 15.281494140625,
                child: GeneratedLeft1Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 138.6494140625,
                right: null,
                bottom: null,
                width: 360.0,
                height: 566.3505859375,
                child: GeneratedDetailsWidget3(),
              ),
              Positioned(
                left: 32.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget9(),
              ),
              Positioned(
                left: 32.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget10(),
              ),
              Positioned(
                left: 32.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget11(),
              )
            ]),
      ),
    ));
  }
}
