import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedWaterWidget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedWaterWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedWaterWidget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedDetailsWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedPlantWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateddetailplantwidget/generated/GeneratedNotTouchWidget5.dart';

/* Frame DetailPlant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailPlantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget5(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 448.0,
                child: GeneratedPlantWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 324.0,
                child: GeneratedDetailsWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 141.0,
                child: GeneratedWaterWidget(),
              ),
              Positioned(
                left: 130.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 141.0,
                child: GeneratedWaterWidget1(),
              ),
              Positioned(
                left: 240.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 141.0,
                child: GeneratedWaterWidget2(),
              )
            ]),
      ),
    ));
  }
}
