import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedNotTouchWidget14.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedLeft1Widget9.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedRectangle8Widget24.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedGroup1Widget11.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedInputFieldDefaultRTEWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedPlantWidget6.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedBarWidget11.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatednotesdetailwidget/generated/GeneratedFrame1Widget12.dart';

/* Frame NotesDetail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotesDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 75.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 205.1928253173828,
                child: GeneratedPlantWidget6(),
              ),
              Positioned(
                left: 20.15999984741211,
                top: 96.95478820800781,
                right: null,
                bottom: null,
                width: 24.0,
                height: 12.666223526000977,
                child: GeneratedLeft1Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 534.0,
                child: GeneratedRectangle8Widget24(),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedBarWidget11(),
              ),
              Positioned(
                left: 32.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 23.0,
                child: GeneratedFrame1Widget12(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget11(),
              ),
              Positioned(
                left: 18.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 479.0,
                child: GeneratedInputFieldDefaultRTEWidget(),
              )
            ]),
      ),
    ));
  }
}
