import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedCalendarWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedLeft1Widget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedUsuarioWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedNotTouchWidget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedInputFieldDefaultWithoutIconWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedContraseaWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedNombreWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generateduserloginwidget/generated/GeneratedIniciarsesinWidget.dart';

/* Frame UserLogin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget2(),
              ),
              Positioned(
                left: 148.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 30.0,
                child: GeneratedUsuarioWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 12.720000267028809,
                child: GeneratedLeft1Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 23.0,
                child: GeneratedIniciarsesinWidget(),
              ),
              Positioned(
                left: 31.639892578125,
                top: 134.0,
                right: null,
                bottom: null,
                width: 274.760009765625,
                height: 30.05976104736328,
                child: GeneratedNombreWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 215.2882080078125,
                right: null,
                bottom: null,
                width: 274.760009765625,
                height: 30.05976104736328,
                child: GeneratedContraseaWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 159.2882080078125,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 240.2882080078125,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget1(),
              ),
              Positioned(
                left: 91.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 36.0,
                child: GeneratedCalendarWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget2(),
              )
            ]),
      ),
    ));
  }
}
