import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedGroup1Widget5.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedInputFieldDefaultWithoutIconWidget8.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedBarWidget5.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedNotTouchWidget8.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedFrame1Widget6.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedRefresh1Widget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedDetailsWidget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedInputFieldDefaultWithoutIconWidget7.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedPlantWidget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedTimeCircle1Widget1.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedInputFieldDefaultWithoutIconWidget6.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedvrplantwidget1/generated/GeneratedRecordWidget1.dart';

/* Frame VRPlant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVRPlantWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget8(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedBarWidget5(),
              ),
              Positioned(
                left: 32.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 23.0,
                child: GeneratedFrame1Widget6(),
              ),
              Positioned(
                left: 63.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedTimeCircle1Widget1(),
              ),
              Positioned(
                left: 161.27999877929688,
                top: 672.313232421875,
                right: null,
                bottom: null,
                width: 26.0,
                height: 26.0,
                child: GeneratedRecordWidget1(),
              ),
              Positioned(
                left: 271.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 15.0,
                child: GeneratedRefresh1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 101.07437133789062,
                child: GeneratedPlantWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 138.6494140625,
                right: null,
                bottom: null,
                width: 360.0,
                height: 566.3505859375,
                child: GeneratedDetailsWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget6(),
              ),
              Positioned(
                left: 32.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget7(),
              ),
              Positioned(
                left: 32.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 30.0,
                child: GeneratedInputFieldDefaultWithoutIconWidget8(),
              )
            ]),
      ),
    ));
  }
}
