import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedsearchwidget5/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedsearchwidget5/generated/GeneratedGroup1Widget8.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedsearchwidget5/generated/GeneratedNotTouchWidget11.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedsearchwidget5/generated/GeneratedBarWidget8.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedsearchwidget5/generated/GeneratedFrame1Widget9.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedBarWidget8(),
              ),
              Positioned(
                left: 32.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 294.0,
                height: 23.0,
                child: GeneratedFrame1Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget11(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 641.0,
                child: GeneratedFrame2Widget(),
              )
            ]),
      ),
    ));
  }
}
