import 'package:flutter/material.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedLeft1Widget7.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedPlantWidget4.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedNotTouchWidget10.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedDetailsWidget4.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedGroup2Widget2.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedCompartirMuestratuplantaalmundoWidget.dart';
import 'package:flutterapp/plantamas_managermovil2app/generatedshareplantwidget/generated/GeneratedGroup1Widget7.dart';

/* Frame SharePlant
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSharePlantWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 46.0,
                child: GeneratedGroup2Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 800.0,
                child: GeneratedNotTouchWidget10(),
              ),
              Positioned(
                left: 13.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 25.0,
                child: GeneratedGroup1Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 103.00265502929688,
                child: GeneratedPlantWidget4(),
              ),
              Positioned(
                left: 19.894775390625,
                top: 91.1328125,
                right: null,
                bottom: null,
                width: 23.6842098236084,
                height: 13.8671875,
                child: GeneratedLeft1Widget7(),
              ),
              Positioned(
                left: 4.547473508864641e-13,
                top: 132.8447265625,
                right: null,
                bottom: null,
                width: 360.0,
                height: 577.1553955078125,
                child: GeneratedDetailsWidget4(),
              ),
              Positioned(
                left: 32.0,
                top: 235.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 385.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 73.0,
                child: GeneratedCompartirMuestratuplantaalmundoWidget(),
              )
            ]),
      ),
    ));
  }
}
